// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "info.h"
#include <string>

std::string info_message = 
	"Frozlunky - Seeds and more for Spelunky!\n"
	"\n"
	"To use Frozlunky, enter a seed consisting of any number of spaces, \n letters, and numbers, and press \"Seed it!\"\n"
	"\n"
	"Frozlunky also has special seeds, which cause \n the Spelunky generator to behave in unique ways.\n"
	"The following are the currently implemented special seeds:\n"
	"\tmediumlunky\n"
	"\tmediumlunky:any custom seed\n"
	"\thardlunky\n"
	"\thardlunky:any custom seed\n"
	"\tinsanelunky\n"
	"\tinsanelunky:any custom seed\n"
	"\tsashavol\n"
	"\tsashavol:any custom seed\n"
	"\n"
	"\n"
	"Frozlunky also features a series of special mods under \"Mods\"\n"
	"-- \"Dark levels are possible on ice caves/hell\" makes\n it possible for dark type levels to be on these level types\n"
	"-- \"All levels are dark\" causes all levels to be dark\n"
	"-- \"Hybrid Enemies Mod allows you to combine enemy types and\n have them behave in strange ways.\"\n"
	"\tTo use, choose an enemy from the drop-down list and press \"Add\"\n"
	"\tYou can do this with multiple enemy types, if you wish to\n\t remove an enemy select it in the list and press \"Remove\"\n"
	"\tTo remove all enemies from the list, select \"Enemy AI\" in\n\t the list and press \"Remove\"\n"
	"\n"
	"\n"
	"The Frozlunky \"Speedrun Daily\" feature's information can be found at http://frozboards.sashavol.com/info.htm"
	"\n"
	"WARNING: Frozlunky disables online interaction\n in Spelunky while\n it is active, you must reset Spelunky to revert this.\n"
	"Developed by Sashavol";

Fl_Double_Window* make_info_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(470, 345, "Frozlunky Info");
    w = o;
    { 
		const char* text = info_message.c_str();
		Fl_Text_Buffer* ftb = new Fl_Text_Buffer(info_message.size());
		ftb->text(text);
		Fl_Text_Display* ftd = new Fl_Text_Display(5, 5, 460, 335);
		ftd->buffer(ftb);
    } // Fl_Text_Display* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
